version: "3.8"

services:
  keycloak:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - keycloak-postgres
    ports:
      - "8080:8080"
    command: ["start-dev"]

  keycloak-postgres:
    image: postgres:14-alpine
    ports:
      - 5434:5434
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/keycloack-data
    environment:
      - POSTGRES_PASSWORD=scantist-keycloak
      - POSTGRES_USER=scantist-keycloak
      - POSTGRES_DB=postgres
    command: -p 5434

networks:
  default:
    external:
      name: scantist-network
